// Generated by AI Site Editor — do not edit by hand.
// Schema lives in .ai-editor/datamodel.json; data lives in data/*.json.

import experienceItemsData from '../data/experience_items.json'

export type ExperienceItem = {
  id: string
  title: string
  company?: string | null
  location?: string | null
  startDate?: string | null
  endDate?: string | null
  description?: string | null
  type?: string | null
  order?: number | null
}

export const experienceItems = experienceItemsData as unknown as ExperienceItem[]
export const getExperienceItems = (): ExperienceItem[] => experienceItems
